# namespace: 
only_fuzz_marked: true
cache_solution: in_memory

restlerwrapper:
  image:
    image: restlerwrapper
    pullPolicy: IfNotPresent
    tag:
  restler:
    time_budget: 0.001
    cpu_limit: 1000m
    memory_limit: 1024Mi
    cpu_request: 1000m
    memory_request: 1024Mi
    telemetry_opt_out: true
auth:
  username: 
  secret: "0d5989ed-d60c-470e-b1b5-576fcf0f5d8c"
redis:
  host_name: "localhost"
  port: 6379
#s3:
#  endpoint_url: "http://release-name-minio:9000"
#  report_bucket: "s3://restler-reports"
#  access_key: "reportwriter"
#  secret_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
#  sidecar:
#    image: "amazon/aws-cli:latest"
#    container_name: "cnfuzz-s3-sidecar"
