## Create persistent volume claim for minio to store data.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-fs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
## Run minio fs deployment.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-fs
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minio-fs
  template:
    metadata:
      labels:
        app: minio-fs
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minio-fs-pvc
      containers:
      - name: minio-fs
        volumeMounts:
        - name: data 
          mountPath: "/data"
        image: minio/minio:latest
        args:
        - server
        - /data
        env:
        - name: MINIO_ROOT_USER
          value: "minio"
        - name: MINIO_ROOT_PASSWORD
          value: "minio123"
        ports:
        - containerPort: 9000
          hostPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio-fs
  labels:
    app: minio-fs
spec:
  type: NodePort
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio-fs
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
spec:
  defaultBackend:
    service:
      name: minio-fs
      port:
        number: 9000
