apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cnfuzz.fullname" . }}
  labels:
    {{- include "cnfuzz.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cnfuzz.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "cnfuzz.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cnfuzz.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args:
            - "--config"
            - {{ $.Values.configFile | default "/config/config.yaml" }}
            - "-d"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
          #livenessProbe:
          #  httpGet:
          #    path: /health/live
          #    port: http
          #  initialDelaySeconds: 3
          #  periodSeconds: 3
          #readinessProbe:
          #  httpGet:
          #    path: /health/ready
          #    port: http
          #  initialDelaySeconds: 3
          #  periodSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: cnfuzz-config
            items:
              - key: "config.yaml"
                path: "config.yaml"
              - key: "auth.py"
                path: "auth.py"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
