apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "restlerwrapper.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "restlerwrapper.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "restlerwrapper.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "restlerwrapper.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cnfuzz.serviceAccountName" . }}-batch
rules:
  - apiGroups:
      - ""
      - "batch"
    resources:
      - jobs
    verbs:
      - get
      - list
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cnfuzz.serviceAccountName" . }}-batch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cnfuzz.serviceAccountName" . }}-batch
subjects:
  - kind: ServiceAccount
    name: {{ include "cnfuzz.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cnfuzz.serviceAccountName" . }}-pods
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - events
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cnfuzz.serviceAccountName" . }}-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cnfuzz.serviceAccountName" . }}-pods
subjects:
  - kind: ServiceAccount
    name: {{ include "cnfuzz.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
