# Default values for cnfuzz.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

redis:
  enabled: true
  architecture: standalone
  replica:
    replicaCount: 1
  auth:
    enabled: false

minio:
  enabled: true
  # Comment (and/or change) any of the following if you want to deploy minio to a production scenario.
  mode: standalone # only use for development/testing
  replicas: 1
  persistence:
    size: 1Gi
  resources:
    requests:
      memory: 1Gi
  buckets:
    - name: restler-reports
      policy: upload
      purge: false
  policies:
    - name: report-getwrite
      statements:
        - actions:
           - 's3:GetObject'
           - 's3:PutObject'
          resources:
           # FIXME: This should be possible with just 'arn:aws:s3:::mybucket', but caused Access Denied errors when I tried it
           - 'arn:aws:s3:::*'
  users:
    - accessKey: reportwriter
      secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      policy: report-getwrite

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

namespace:
onlyMarked: true
# cache_solution: "redis" # in_memory or redis

redisCnf:
  port: 6379

restler:
  timeBudget: "1" # hour
  resources:
    limits:
      cpu: 1000 # m
      memory: 1024 # Mi
    requests:
      cpu: 1000 # m
      memory: 1024 # Mi
  telemetryOptOut: true

auth:
  username:
  secret:

s3:
  # TODO use the AWS_DEFAULT_REGION env variable instead and leave 'endpoint' arg empty
  # https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
  endpoint: "" # https://s3-accesspoint.eu-west-1.amazonaws.com
  bucket: "" # s3://your-s3-bucket
  accessKey: "" # AKIAIOSFODNN7EXAMPLE
  secretKey: "" # wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  sidecar:
    image:
      repository: amazon/aws-cli
      tag: latest
    name: cnfuzz-s3-sidecar

controllerImage:
  repository: ghcr.io/suecodelabs/cnfuzz
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

restlerwrapper:
  image:
    image: ghcr.io/suecodelabs/cnfuzz-restlerwrapper
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "cnfuzz"

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  #readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
