name: "Kubernetes Integration"
on:
  pull_request:
    branches:
      - main
      - "releases/**"
  push:

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: pcktdmp
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Testing
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
          make kind
